### ISSUE TITLE
don't convert now

### ISSUE THREAD

**Issue by maikerux** [EmmanuelBeziat/bns-profile#10]
i click convert now and nothing...

**Comment by EmmanuelBeziat** [comment]
Hi,

Give me your 2 images, so I can check them. I’ll also convert it for you. :)

**Comment by EmmanuelBeziat** [comment]
Also, remember that your images must be in JPG format.

**Comment by epikGG-zz** [comment]
Hey how can i unsub when idk my login im sick of these emails delete my acc pls

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EmmanuelBeziat** [comment]
I can't delete your account, but you have a link in the mail you just copied, at the bottom:

**Comment by epikGG-zz** [comment]
[Image]



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
