### ISSUE TITLE
Custom image removed

### ISSUE THREAD

**Issue by highattack30** [EmmanuelBeziat/bns-profile#11]
I found an issue when the photo uploaded when I press refresh I see it but after like 5 minutes It's gone
this happened while I'm in the game and even if I restart or shutdown the game
using the official website:

https://bns-profile.surge.sh

**Comment by EmmanuelBeziat** [comment]
Hi,

I’m sorry, but I can’t help with that; if your picture is removed from the game after it was successfully loaded once, then it’s probably manually removed by a GM.

Feel free to add more details if needed :)
