### ISSUE TITLE
Can't convert my image

### ISSUE THREAD

**Issue by YvanChauvy** [EmmanuelBeziat/bns-profile#12]
Hi,
when i place the 2 image  i try to click on convert but nothink ...
I send you the image if it can help you :
![portrait_170929_000](https://user-images.githubusercontent.com/28706028/31141934-23f96ac2-a879-11e7-89b1-c633c40d5044.jpg)
![gunner](https://user-images.githubusercontent.com/28706028/31141939-27bcdc7a-a879-11e7-9bf6-021584e700b1.png)
 
thanks

**Comment by EmmanuelBeziat** [comment]
Salut,

Voilà ton image finale, enregistre-la dans ton dossier `CharacterShots`. :)

![](http://image.noelshack.com/fichiers/2017/40/3/1507102876-bns-profile-2017-10-04-09-39.jpg)

Pour info, ça ne fonctionnait pas parce que l’image que tu envoyais (pas celle issue de BnS, l’autre) était au format PNG et non en JPG. C’est précisé dans la FAQ, mais c’est vrai que ce n’est pas immédiatement précisé… Il faudrait que j’ajoute un message d’erreur (ou que je parvienne à faire un système de conversion à la volée).
