### ISSUE TITLE
uhh bns tool issue

### ISSUE THREAD

**Issue by epikGG** [EmmanuelBeziat/bns-profile#4]
Hey, seems no matter what I do I can't get your picture tool to work. I take a fresh picture ingame, I took a screenshot from ingame and resized it to 378x620 JPG. Uploaded both in the same order, saved the picture that your tool/site created as 'download' (JPEG) in Character Shot folder. I go back into game and I don't see the picture I uploaded as it says I should in your guide/tutorial. Also when I registed the fresh/valid picture it just uses that exact picture. Please help i'm pulling my hair out over this :(

Also I don't know how this works but I thought maybe because I am using WTFast maybe it could be interfering somehow? I tried without WTFast and no luck either but thought maybe it's worth suggesting lol.

Edit: Using google chrome and windows 10 if thats of any use. Thanks.

**Comment by EmmanuelBeziat** [comment]
Hi,
I just tried to check if it hasn't Something to do with the update of yesterday, but it's working fine.

Please, post your legit character shot, your custom image, and the image you get as a result, so i can check where this goes wrong. :)

**Comment by epikGG** [comment]
Hey bud thanks for the quick reply, appreciate it.

Ok so here is valid pic: http://imgur.com/a/zNJbI
Here is what I want to have: http://imgur.com/a/DyFKd
This is what the site gives and I place that in character shot: http://imgur.com/a/D7cut

Thanks again.

**Comment by EmmanuelBeziat** [comment]
I can't find why, but the problem seems to come from the valid pic. When I try with some I take myself, it works fine.

Here's your image : 

![](http://image.noelshack.com/fichiers/2016/37/1474031626-epikgg-profile.jpg)

Tell me if it work

**Comment by epikGG** [comment]
Thanks, so I'm not doing something wrong what a relief, somewhat haha. Just about to jump on the pc will let you know in a tick

**Comment by epikGG** [comment]
Hey, didn't work either. I just took a fresh picture ingame now. 
http://imgur.com/a/7srXj

I uploaded fresh, chose same custom pic from my desktop, and downloaded your pic for character shot folder and didn't work either. Not sure.

**Comment by EmmanuelBeziat** [comment]
I just don't get why this isn't working. I just tried again with a fresh new ingame picture, and it worked. 

Strange thing is, your legit CharacterShot is 413×678px, mine are 386×633. For some reason, these are not the same "pictures types", and I don't know why, but that must be the cause of the problem. Are you on EU or US server? I don't know if it could matter, but i'm exploring any possibility…

**Comment by EmmanuelBeziat** [comment]
Can you try with this one as a legit ?

![](http://image.noelshack.com/fichiers/2016/37/1474035944-portrait-160916-000.jpg)

**Comment by epikGG** [comment]
Sure, do I just copy this into my Character Shot and then do normal process?

**Comment by epikGG** [comment]
Hmm, copying it into my folder, it doesnt appear in portraits, what do I do step by step sorry ;x

**Comment by epikGG** [comment]
I noticed after i copied this pic into my folder there is a blue line on my old picture on right hand side you can see it ingame, dunno if thats a clue xD 

http://imgur.com/a/to89Q

**Comment by epikGG** [comment]
Aight, scrap all that above. I renamed your pic above to portrait_002 etc and I could use that picture, but when i tried the normal method using that pic as valid pic, it doesn't change anything still ;/

**Comment by EmmanuelBeziat** [comment]
That's really strange.

Can you test this tool to see if it does the job? It's the same process (but watch out, it will try to open a new tab to give you the final image, your adblocker will surely stop it. You'll just have to click on "authorize" at the top right of your browser) : http://f4rnham.github.io/BnS_pictures/

**Comment by epikGG** [comment]
Yeah it sucks, maybe I should reinstall BnS? I've tried that 50 times before someone linked me to this site doesn't work either. I just tried it with your pic as valid and still no good :(

**Comment by EmmanuelBeziat** [comment]
This is crazy… But reinstall BnS would take you hours !

**Comment by epikGG** [comment]
Hmm either that or you could log my account maybe? xD

**Comment by EmmanuelBeziat** [comment]
I don't know if I can. It depend if you’re on US or EU servers, i guess.

If you wanna give it a try, I suggest you change your password first, so you don’t post and give your original one. Then you’ll change it back when done. This is just a safety check.
