### ISSUE TITLE
Unable to Convert

### ISSUE THREAD

**Issue by Unimportance** [EmmanuelBeziat/bns-profile#6]
For whatever reason for the past two days I've been unable to finish converting my display picture. I've used your website before with no issues. I have both the valid Blade and Soul character shot and my resized custom image in the correct place, but whenever I click convert, nothing happens. I've tried to reload the page several times, tried on two separate occasions and still to no avail. Is this an actual problem, or am I doing something wrong?

**Comment by EmmanuelBeziat** [comment]
Hi,
Which browser do you use, please?

**Comment by Unimportance** [comment]
Google Chrome

**Comment by EmmanuelBeziat** [comment]
Nothing have been reported about this, but I tried anyway; no problem on Chrome macOS or Windows…

This is very strange. Give me your two pictures, and I'll do it for you. :)

**Comment by Darkzero3802** [comment]
Yea same issue with Chrome. Click the button and nothing happens. When trying on IE the options to select a pic doesnt show at all its just the simple site wording that shows.

**Comment by EmmanuelBeziat** [comment]
That’s one hell of a bug here… Shit.

Please, see in the #7 if you can help me find out what’s going on with the little steps I suggested. :)
