### ISSUE TITLE
Convert Failure

### ISSUE THREAD

**Issue by Darkzero3802** [EmmanuelBeziat/bns-profile#7]
This is basically the same Chrome issue as the last bug report. Put the pics in, everything is as it should be, click convert now and nothing happens the page doesnt load anything. When trying IE the option to select the pic doesnt even load up on the web page.

**Comment by EmmanuelBeziat** [comment]
@Darkzero3802 Thanks for pointing this out.

I can’t reproduce the issue, that’s frustrating… Can you please try this:

1. Go on the website with Chrome and open the console (ctrl + shift + j)
2. Try to do the conversion
3. If the conversion fail, is there anything written in the console? If so, please take a screenshot and put it here

Thanks!

**Comment by jarretthuang** [comment]
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at VueComponent.UpdateChecksum (https://bns-profile.surge.sh/static/js/app.d4200450ccfb4a1491b4.js:10:3938)
    at VueComponent.UpdateChecksum (https://bns-profile.surge.sh/static/js/vendor.4ff40ada644a14fb4624.js:23:1149)
    at HTMLImageElement.n.onload (https://bns-profile.surge.sh/static/js/app.d4200450ccfb4a1491b4.js:10:3656)

**Comment by EmmanuelBeziat** [comment]
@jarretthuang Thanks for the list, I think I know what’s going on now… Just have to find why.

Can you give me the picture you used, I need to see what is different from the ones that work... Also, which version of the game do you use (country)?
