### ISSUE TITLE
white page

### ISSUE THREAD

**Issue by DemonRem** [EmmanuelBeziat/bns-profile#9]
why my website page is white?

**Comment by EmmanuelBeziat** [comment]
When you’re going to https://bns-profile.surge.sh/ ?

**Comment by DemonRem** [comment]
Yes


בתאריך 17 בספט׳ 2017 11:46 PM,‏ "Emmanuel Béziat" <notifications@github.com>
כתב:

**Comment by EmmanuelBeziat** [comment]
That's weird; what browser so you use? Have you tried with another one, just in case?
